---
fail_fast: true
exclude: \.terraform/|\.terragrunt-cache/
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.16
    hooks:
      - id: terraform-validate
        always_run: true
      - id: markdown-link-check
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.52.0
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terraform_docs
      - id: terraform_tfsec
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.0.504
    hooks:
      - id: checkov
        args: ['--skip-check=CKV_DOCKER_2,CKV2_GCP_3']
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.29.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-symlinks
      - id: no-commit-to-branch
        args: [--branch, main]
